const currencys = {
	ANG: 'Netherlands Antillean Guilder',
	SVC: 'Salvadoran Colón',
	CAD: 'Canadian Dollar',
	XCD: 'East Caribbean Dollar',
	MVR: 'Maldivian Rufiyaa',
	HRK: 'Croatian Kuna',
	AUD: 'Australian Dollar',
	MWK: 'Malawian Kwacha',
	XAG: 'Silver (troy ounce)',
	MAD: 'Moroccan Dirham',
	PHP: 'Philippine Peso',
	NAD: 'Namibian Dollar',
	GNF: 'Guinean Franc',
	KES: 'Kenyan Shilling',
	MZN: 'Mozambican Metical',
	BTN: 'Bhutanese Ngultrum',
	MGA: 'Malagasy Ariary',
	AZN: 'Azerbaijani Manat',
	XAU: 'Gold (troy ounce)',
	RON: 'Romanian Leu',
	CHF: 'Swiss Franc',
	EGP: 'Egyptian Pound',
	BSD: 'Bahamian Dollar',
	TWD: 'New Taiwan Dollar',
	GGP: 'Guernsey Pound',
	LVL: 'Latvian Lats',
	MMK: 'Burmese Kyat',
	WST: 'Samoan Tala',
	ILS: 'Israeli New Shekel',
	BHD: 'Bahraini Dinar',
	GBP: 'British Pound Sterling',
	TZS: 'Tanzanian Shilling',
	SDG: 'Sudanese Pound',
	LAK: 'Lao Kip',
	DJF: 'Djiboutian Franc',
	BYN: 'Belarusian Ruble',
	LBP: 'Lebanese Pound',
	RWF: 'Rwandan Franc',
	PEN: 'Peruvian Sol',
	EUR: 'Euro',
	ZMK: 'Zambian Kwacha (pre-2013)',
	RSD: 'Serbian Dinar',
	INR: 'Indian Rupee',
	MUR: 'Mauritian Rupee',
	BWP: 'Botswana Pula',
	GEL: 'Georgian Lari',
	KMF: 'Comorian Franc',
	UZS: 'Uzbekistani Som',
	RUB: 'Russian Ruble',
	CUC: 'Cuban Convertible Peso',
	BGN: 'Bulgarian Lev',
	JOD: 'Jordanian Dinar',
	NGN: 'Nigerian Naira',
	BDT: 'Bangladeshi Taka',
	PKR: 'Pakistani Rupee',
	BRL: 'Brazilian Real',
	KZT: 'Kazakhstani Tenge',
	CVE: 'Cape Verdean Escudo',
	HNL: 'Honduran Lempira',
	NZD: 'New Zealand Dollar',
	ERN: 'Eritrean Nakfa',
	NPR: 'Nepalese Rupee',
	ZMW: 'Zambian Kwacha',
	FKP: 'Falkland Islands Pound',
	DZD: 'Algerian Dinar',
	JMD: 'Jamaican Dollar',
	CRC: 'Costa Rican Colón',
	GMD: 'Gambian Dalasi',
	PLN: 'Polish Zloty',
	AMD: 'Armenian Dram',
	BMD: 'Bermudian Dollar',
	BZD: 'Belize Dollar',
	BBD: 'Barbadian Dollar',
	SBD: 'Solomon Islands Dollar',
	IDR: 'Indonesian Rupiah',
	ALL: 'Albanian Lek',
	IQD: 'Iraqi Dinar',
	BIF: 'Burundian Franc',
	HKD: 'Hong Kong Dollar',
	GIP: 'Gibraltar Pound',
	BAM: 'Bosnia-Herzegovina Convertible Mark',
	LKR: 'Sri Lankan Rupee',
	QAR: 'Qatari Rial',
	SAR: 'Saudi Riyal',
	TOP: 'Tongan Paʻanga',
	SEK: 'Swedish Krona',
	ZAR: 'South African Rand',
	ARS: 'Argentine Peso',
	MYR: 'Malaysian Ringgit',
	BYR: 'Belarusian Ruble (pre-2016)',
	KPW: 'North Korean Won',
	CZK: 'Czech Koruna',
	STD: 'São Tomé and Príncipe Dobra (pre-2018)',
	BTC: 'Bitcoin',
	ZWL: 'Zimbabwean Dollar',
	LSL: 'Lesotho Loti',
	COP: 'Colombian Peso',
	PAB: 'Panamanian Balboa',
	IRR: 'Iranian Rial',
	CNH: 'Chinese Yuan (Offshore)',
	NOK: 'Norwegian Krone',
	XPF: 'CFP Franc',
	XOF: 'West African CFA Franc',
	XDR: 'Special Drawing Rights',
	OMR: 'Omani Rial',
	CNY: 'Chinese Yuan',
	NIO: 'Nicaraguan Córdoba',
	AOA: 'Angolan Kwanza',
	SCR: 'Seychellois Rupee',
	MOP: 'Macanese Pataca',
	ISK: 'Icelandic Króna',
	VND: 'Vietnamese Dong',
	VES: 'Venezuelan Bolívar Soberano',
	USD: 'United States Dollar',
	UYU: 'Uruguayan Peso',
	VEF: 'Venezuelan Bolívar (pre-2018)',
	MRU: 'Mauritanian Ouguiya',
	UGX: 'Ugandan Shilling',
	DOP: 'Dominican Peso',
	UAH: 'Ukrainian Hryvnia',
	BOB: 'Bolivian Boliviano',
	TTD: 'Trinidad and Tobago Dollar',
	KGS: 'Kyrgyzstani Som',
	TND: 'Tunisian Dinar',
	SGD: 'Singapore Dollar',
	TMT: 'Turkmenistani Manat',
	GHS: 'Ghanaian Cedi',
	TJS: 'Tajikistani Somoni',
	KHR: 'Cambodian Riel',
	ETB: 'Ethiopian Birr',
	PGK: 'Papua New Guinean Kina',
	THB: 'Thai Baht',
	AED: 'United Arab Emirates Dirham',
	GTQ: 'Guatemalan Quetzal',
	LRD: 'Liberian Dollar',
	SYP: 'Syrian Pound',
	KYD: 'Cayman Islands Dollar',
	SRD: 'Surinamese Dollar',
	HTG: 'Haitian Gourde',
	LYD: 'Libyan Dinar',
	SLL: 'Sierra Leonean Leone',
	SLE: 'Sierra Leonean Leone (new)',
	SHP: 'Saint Helena Pound',
	IMP: 'Isle of Man Pound',
	FJD: 'Fijian Dollar',
	PYG: 'Paraguayan Guarani',
	KRW: 'South Korean Won',
	SZL: 'Swazi Lilangeni',
	GYD: 'Guyanese Dollar',
	MDL: 'Moldovan Leu',
	MXN: 'Mexican Peso',
	CLP: 'Chilean Peso',
	LTL: 'Lithuanian Litas',
	SOS: 'Somali Shilling',
	MNT: 'Mongolian Tögrög',
	AFN: 'Afghan Afghani',
	CUP: 'Cuban Peso',
	CLF: 'Unidad de Fomento (Chile)',
	JPY: 'Japanese Yen',
	TRY: 'Turkish Lira',
	YER: 'Yemeni Rial',
	HUF: 'Hungarian Forint',
	BND: 'Brunei Dollar',
	JEP: 'Jersey Pound',
	MKD: 'Macedonian Denar',
	AWG: 'Aruban Florin',
	CDF: 'Congolese Franc',
	VUV: 'Vanuatu Vatu',
	XAF: 'Central African CFA Franc',
	KWD: 'Kuwaiti Dinar',
	DKK: 'Danish Krone'
};

export default currencys;
